name: Build and Publish Rocky8 Sysroot

on:
  push:
      branches: [ main ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # needed to create/releases & upload assets
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create tag
        run: |
          git tag sysroot-rocky8-${{ github.run_id }}
          git push origin sysroot-rocky8-${{ github.run_id }}

      - name: Pull Rocky 8 image
        run: docker pull rockylinux:8

      - name: Create container and install dev packages
        run: |
          docker run --name rocky8-dev \
            -d rockylinux:8 sleep 3600
          docker exec rocky8-dev bash -c "dnf -y update && dnf install -y glibc-devel libstdc++-devel kernel-headers && dnf clean all"
          # give dnf time to finish and ensure container remains
          sleep 2

      - name: Export filesystem
        run: |
          mkdir -p sysroot-full
          docker export rocky8-dev | tar -C sysroot-full -xf -

      - name: Build minimal sysroot
        run: |
          mkdir -p sysroot-min/usr
          rsync -a sysroot-full/usr/include sysroot-min/usr/
          rsync -a sysroot-full/usr/lib* sysroot-min/usr/ || true
          rsync -a sysroot-full/lib* sysroot-min/ || true

          rm -rf sysroot-min/usr/share/{man,doc,info,locale} || true

          tar --numeric-owner -C sysroot-min -czf rocky8-sysroot.tar.gz .

      - name: Compute sha256
        id: sha
        run: |
          sha256sum rocky8-sysroot.tar.gz | awk '{print $1}' > sha256.txt
          echo "sha256=$(cat sha256.txt)" >> $GITHUB_OUTPUT

      - name: Create or update release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: sysroot-rocky8-${{ github.run_id }}
          name: "rocky8-sysroot-${{ github.run_id }}"
          body: "Automated sysroot build - run ${{ github.run_id }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload sysroot asset to release
        uses: softprops/action-gh-release@v1
        with:
          files: rocky8-sysroot.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Print artifact metadata
        run: |
          echo "sysroot_url: https://github.com/${{ github.repository }}/releases/download/sysroot-rocky8-${{ github.run_id }}/rocky8-sysroot.tar.gz"
          echo "sha256: ${{ steps.sha.outputs.sha256 }}"

